<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="WebServiceTestSuite" duration-ms="24162" started-at="2019-08-14T18:30:45Z" finished-at="2019-08-14T18:31:09Z">
    <groups>
    </groups>
    <test name="RESTAPITest" duration-ms="24162" started-at="2019-08-14T18:30:45Z" finished-at="2019-08-14T18:31:09Z">
      <class name="tests.TestPUTRequest">
        <test-method status="PASS" signature="testPUTRequestDetails()[pri:0, instance:tests.TestPUTRequest@64729b1e]" name="testPUTRequestDetails" duration-ms="5380" started-at="2019-08-14T18:30:59Z" finished-at="2019-08-14T18:31:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPUTRequestDetails -->
      </class> <!-- tests.TestPUTRequest -->
      <class name="tests.TestPOSTRequest">
        <test-method status="PASS" signature="setup()[pri:0, instance:tests.TestPOSTRequest@2d6eabae]" name="setup" is-config="true" duration-ms="18" started-at="2019-08-14T18:30:44Z" finished-at="2019-08-14T18:30:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="testPOSTRequestDetails()[pri:0, instance:tests.TestPOSTRequest@2d6eabae]" name="testPOSTRequestDetails" duration-ms="5641" started-at="2019-08-14T18:30:53Z" finished-at="2019-08-14T18:30:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPOSTRequestDetails -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.TestPOSTRequest@2d6eabae]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-08-14T18:31:09Z" finished-at="2019-08-14T18:31:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.TestPOSTRequest -->
      <class name="tests.TestGETRequest">
        <test-method status="FAIL" signature="testGETUserDetails()[pri:0, instance:tests.TestGETRequest@4e7dc304]" name="testGETUserDetails" duration-ms="8483" started-at="2019-08-14T18:30:45Z" finished-at="2019-08-14T18:30:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Name does not match expected [Eve2] but found [Eve]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Name does not match expected [Eve2] but found [Eve]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at tests.TestGETRequest.testGETUserDetails(TestGETRequest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGETUserDetails -->
      </class> <!-- tests.TestGETRequest -->
      <class name="tests.TestDELETERequest">
        <test-method status="PASS" signature="testDELETERequestDetails()[pri:0, instance:tests.TestDELETERequest@10bbd20a]" name="testDELETERequestDetails" duration-ms="4451" started-at="2019-08-14T18:31:04Z" finished-at="2019-08-14T18:31:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDELETERequestDetails -->
      </class> <!-- tests.TestDELETERequest -->
    </test> <!-- RESTAPITest -->
  </suite> <!-- WebServiceTestSuite -->
</testng-results>
